# Generated by Django 3.0.5 on 2020-04-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmapsdisplay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('stop_points', models.ManyToManyField(to='gmapsdisplay.Address')),
            ],
        ),
    ]
