# Generated by Django 3.0.5 on 2020-04-05 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmapsdisplay', '0002_deliveryroute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='deliveryroute',
            name='stop_points',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmapsdisplay.DeliveryRoute'),
        ),
    ]
